#version 460

layout(local_size_x = 16, local_size_y = 16) in;

layout(rgba16f, set = 0, binding = 0) uniform image2D image;

layout(push_constant) uniform constants
{
    vec4 color_a;
    vec4 color_b;
} pc;

void main()
{
    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(image);

    vec4 color = vec4(0.0, 0.0, 0.0, 1.0);

    if (gl_LocalInvocationID.x != 0 && gl_LocalInvocationID.y != 0)
    {
        float t_x = float(gl_GlobalInvocationID.x) / float(size.x);
        float t_y = float(gl_GlobalInvocationID.y) / float(size.y);

        vec4 color_x = pc.color_a + t_x * (pc.color_b - pc.color_a);
        vec4 color_y = pc.color_a + t_y * (pc.color_b - pc.color_a);

        color = 0.5f * (color_x + color_y);
    }

    imageStore(image, uv, color);
}
